services:
  patient-db:
    image: postgres
    container_name: patient-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient_db
    ports:
      - "5432:5432"

  admin-db:
    image: postgres
    container_name: admin-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: admin_db
    ports:
      - "5433:5432" 